- name: Add Node key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes

- name: Add Node repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_8.x xenial main'
    update_cache: yes
  become: yes

- name: Install Node latest
  apt:
    pkg: node.js
    state: present
    update_cache: yes
